### ISSUE TITLE
Directors' Report required for 2019-2020

### ISSUE THREAD

**Issue by Hibby** [hackerdeen/meetings#14]
We need to publish a Directors' Report for this year covering all major activities:

- Move to Kettock Lodge
- Tax/HMRC Discussions
- Membership Numbers / Changes
- Wiki Move
- Uhhh?

Due by 2020-05-03

**Comment by AndyGaskell** [comment]
I can do the first two if that's ok with folk

**Comment by AndyGaskell** [comment]
Hiya
I've started filling out the directors report.

Some things I'm not sure about...
# How many members we have?
# What is the average paying member count (last 3-month avg)?
# How much we pay in rent to AAD?
# How much we bill in rent to AAD?

I was thinking the first two I'd get from HackHub, but that seems to be down for me at the moment.

The second two, is it ok to publish that in the report do you think?

@Hibby @adventureloop @Nordln @Midder-57N 

It's in git at... 
https://github.com/hackerdeen/meetings/blob/master/2020/20-05-04-directors-report.md
...I'm still adding bits to it, but will try and get it fairly fleshed out by this evening.

**Comment by Hibby** [comment]
> I was thinking the first two I'd get from HackHub, but that seems to be down for me at the moment.

Checking if this is the certificate error that pops up and asking certbot to fix it, please hold,caller!

**Comment by Hibby** [comment]
> 
> 
> > I was thinking the first two I'd get from HackHub, but that seems to be down for me at the moment.
> 
> Checking if this is the certificate error that pops up and asking certbot to fix it, please hold,caller!

This has now been fixed, IPv6 had to be disabled on Finzean for it to get a certificate.

**Comment by AndyGaskell** [comment]
Thanks @Hibby not getting a "The page isn't redirecting properly" error now

**Comment by AndyGaskell** [comment]
Hi, @Hibby @adventureloop @Nordln @Midder-57N

I think it's probably 90% there now, so hopefully we've broken the back of what needed done by Monday with it.

Could someone have a look over it please? Just to check for any mistakes, glaring or minor, and if I've missed anything.

It's in git at...
https://github.com/hackerdeen/meetings/blob/master/2020/20-05-04-directors-report.md
...I wont make any more edits, to avoid merge pain.

There are a few bits marked "tbc" in it.

So make edits or jot notes and thoughts here, as you prefer.

Thanks

**Comment by AndyGaskell** [comment]
guess it's done now really :)
